#!/bin/bash

# ".sehirler" adindaki dosyaniz yoksa, ya da guncellemek isterseniz su komutu bir terminalde calistirabilirsiniz:
# for i in $(seq 9146 9955); do sehir=$(curl -s namazvakitleri.diyanet.gov.tr/tr-TR/$i/ | grep "İçin Haftalık Namaz Vakitleri" | awk '{print $7}' | tr '\n' ' '); echo -n ${sehir^^}""; echo $i; done | tee .sehirler
SEHIRLER_DOSYASI=$HOME/.sehirler #indirdiginiz ".sehirler" dosyasinin yeri

if [ -z "$1" ]; then
    sehir=İSTANBUL #varsayilan sehri buradan degistirebilirsiniz
else
    sehir=$1
fi
    
SEHIR=${sehir^^} #sehir ismini buyuk harfe cevir

VAKIT_L1="$SEHIR NAMAZ VAKİTLERİ"
VAKIT_L2="İMSAK GÜNEŞ ÖĞLE İKİNDİ AKŞAM YATSI"
SEHIR_KODU=$(grep $SEHIR $SEHIRLER_DOSYASI | awk '{print $2}')
VAKIT=$(curl -s http://namazvakitleri.diyanet.gov.tr/tr-TR/$SEHIR_KODU | grep tpt-time | head -n 7 | grep -Eo '[0-9][0-9]:[0-9][0-9]' | tr '\n' ' ')

if [ "$VAKIT" == "" ]; then #sonuc yok ise
    echo "NOT: $SEHIR için namaz vakitlerine"
    echo "ulaşılamamaktadır. Lütfen internet"
    echo "bağlantınızı kontrol edin ve şehir"
    echo "ismini küçük İngilizce karakterker-"
    echo "lerle \"$0 kahramanmaraş\" şek-"
    echo "yazdığınızdan emin olun."
    echo
    echo "Bu sonuçlar en son çalıştırma sıra-"
    echo "sında kaydedilmiştir."
    echo 
    cat .vakit
else                        #sonuc var ise
    echo $VAKIT_L1 | tee .vakit
    echo $VAKIT_L2 | tee -a .vakit
    echo $VAKIT | tee -a .vakit
    echo >> .vakit
    echo "Kayıt tarihi: $(date)" >> .vakit
fi
